### ISSUE TITLE
odpwatcher.ODPRefreshProvider incompatible with Neon

### ISSUE THREAD

**Issue by lauri-laanti-heeros** [OpenNTF/org.openntf.nsfodp#126]
This line: https://github.com/OpenNTF/org.openntf.nsfodp/blob/develop/eclipse/plugins/org.openntf.nsfodp.designer.odpwatcher/src/org/openntf/nsfodp/designer/odpwatcher/ODPRefreshProvider.java#L70

uses the new Oxygen method:
https://help.eclipse.org/oxygen/ntopic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/core/resources/refresh/RefreshProvider.html#resetMonitors-org.eclipse.core.resources.IResource-org.eclipse.core.runtime.IProgressMonitor-

...which does not exist in Neon:
https://help.eclipse.org/neon/ntopic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/core/resources/refresh/RefreshProvider.html

**Comment by jesse-gallagher** [comment]
Hmm, I'll have to mull over what to do about that. Maybe there's an abstract implementation class I can piggyback on... otherwise, it'll be forever difficult to deal with, since some of the plugins target Neon-era Designer and others target Oxygen+-era Eclipse.
