### ISSUE TITLE
GitHub Releases - Missing NSFODP-Tooling zip for 2.1.0

### ISSUE THREAD

**Issue by eivindr** [OpenNTF/org.openntf.nsfodp#182]
Could the nsf tooling zip be embedded to the 2.1.0 release (in github releases) the same way as the 2.0.0 release?

..or create a for-dummies documentation on how to compile the Domino feature/plugin jars for 2.1.0? :)

**Comment by jesse-gallagher** [comment]
Ah, indeed - I’ll add that when I get a chance. In the mean time, the packages version is up at its OpenNTF home at https://www.openntf.org/main.nsf/project.xsp?r=project/NSF%20ODP%20Tooling/releases/56296C3743ACEEEB8525841100493194
